# Generated by Django 4.2 on 2023-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(null=True, upload_to='audio_file')),
                ('exported_file', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
